project:
  type: website
  output-dir: docs
website:
  title: "CURE ID"
  navbar:
    left:
      - href: "index.qmd"
        text: "Home"
      - href: "about.qmd"
        text: "About"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
